### ISSUE TITLE
Inviting users seems to be case sensitive

### ISSUE THREAD

**Issue by jessehouwing** [report-uri/report-uri-bugs#60]
When inviting a user to a team like this: `Me@example.org`, they won't be able to access the team. Inviting them with `me@example.org` solves the issues.

Along the same lines, I can invite both `Me@example.org` and `me@example.org`, looks like the check for already existing users is also case sensitive.

**Comment by ScottHelme** [comment]
This is fixed and the change should land within a few minutes.

**Comment by jessehouwing** [comment]
This is still broken for users who register their account with a couple of capital letters in it. So when registering, the address should be normalized and when checking group membership the address should be normalized.

When I try to add them, their lower case version is added (great), but the team doesn't show up in their team settings. I can't add the mixed case version (is normalized), and they can't edit their sign-on address.
